import type { ProjectDocument } from './projectTypes'

export const mockProject: ProjectDocument = {
  metadata: {
    id: 'project-001',
    title: '主动运输示意图',
    description: '用于第一版编辑器开发的示例工程数据',
    themeType: 'membrane_transport',
    contentVersion: 1,
  },

  canvas: {
    width: 1200,
    height: 800,
    background: '#ffffff',
    zoom: 1,
    panX: 0,
    panY: 0,
    showGrid: false,
  },

  objects: [
    {
      id: 'region-outside',
      type: 'region',
      name: 'outside-region',
      x: 80,
      y: 180,
      width: 1040,
      height: 180,
      visible: true,
      label: '膜外',
      regionRole: 'outside',
      backgroundStyle: '#eef7ff',
      zIndex: 1,
    },
    {
      id: 'region-inside',
      type: 'region',
      name: 'inside-region',
      x: 80,
      y: 440,
      width: 1040,
      height: 180,
      visible: true,
      label: '膜内',
      regionRole: 'inside',
      backgroundStyle: '#f4fff1',
      zIndex: 1,
    },
    {
      id: 'membrane-1',
      type: 'membrane',
      name: 'cell-membrane',
      x: 80,
      y: 360,
      width: 1040,
      height: 80,
      visible: true,
      label: '细胞膜',
      showBilayerDetail: true,
      styleVariant: 'basic',
      zIndex: 2,
    },
    {
      id: 'protein-1',
      type: 'protein',
      name: 'carrier-protein',
      x: 560,
      y: 330,
      width: 80,
      height: 140,
      visible: true,
      label: '载体蛋白',
      proteinType: 'carrier',
      active: true,
      requiresATP: true,
      zIndex: 3,
    },
    {
      id: 'particle-1',
      type: 'particle',
      name: 'sodium-particles',
      x: 300,
      y: 260,
      width: 180,
      height: 60,
      visible: true,
      label: 'Na+',
      particleName: 'Na+',
      color: '#4A90E2',
      size: 14,
      count: 6,
      shape: 'circle',
      sourceRegionId: 'region-outside',
      targetRegionId: 'region-inside',
      movable: true,
      zIndex: 4,
    },
    {
      id: 'marker-1',
      type: 'marker',
      name: 'atp-marker',
      x: 670,
      y: 300,
      width: 80,
      height: 30,
      visible: true,
      markerType: 'atp',
      text: 'ATP',
      color: '#ff9f1c',
      zIndex: 5,
    },
    {
      id: 'text-1',
      type: 'text',
      name: 'title-text',
      x: 80,
      y: 80,
      visible: true,
      text: '主动运输示意图',
      fontSize: 28,
      color: '#1f2937',
      align: 'left',
      fontWeight: 'bold',
      zIndex: 10,
    },
    {
      id: 'arrow-1',
      type: 'arrow',
      name: 'direction-arrow',
      x: 500,
      y: 270,
      visible: true,
      x2: 690,
      y2: 520,
      color: '#d64545',
      lineWidth: 3,
      arrowStyle: 'solid',
      label: '逆浓度梯度',
      zIndex: 6,
    },
  ],

  steps: [
    {
      id: 'step-1',
      name: '初始状态',
      description: '展示膜内外区域、载体蛋白和膜外粒子分布',
      actionIds: ['action-1', 'action-2', 'action-3'],
      order: 1,
    },
    {
      id: 'step-2',
      name: '粒子接近载体',
      description: '粒子向载体蛋白移动',
      actionIds: ['action-4'],
      order: 2,
    },
    {
      id: 'step-3',
      name: '穿膜运输',
      description: '粒子在 ATP 参与下跨膜移动到膜内',
      actionIds: ['action-5', 'action-6'],
      order: 3,
    },
  ],

  actions: [
    {
      id: 'action-1',
      type: 'show',
      targetId: 'membrane-1',
      stepId: 'step-1',
    },
    {
      id: 'action-2',
      type: 'show',
      targetId: 'protein-1',
      stepId: 'step-1',
    },
    {
      id: 'action-3',
      type: 'show',
      targetId: 'particle-1',
      stepId: 'step-1',
    },
    {
      id: 'action-4',
      type: 'move',
      targetId: 'particle-1',
      stepId: 'step-2',
      from: { x: 300, y: 260 },
      to: { x: 470, y: 320 },
      duration: 1000,
      easing: 'ease-in-out',
    },
    {
      id: 'action-5',
      type: 'move',
      targetId: 'particle-1',
      stepId: 'step-3',
      from: { x: 470, y: 320 },
      to: { x: 700, y: 500 },
      duration: 1200,
      easing: 'ease-in-out',
    },
    {
      id: 'action-6',
      type: 'change_property',
      targetId: 'marker-1',
      stepId: 'step-3',
      changes: {
        color: '#22c55e',
        text: 'ATP 已消耗',
      },
    },
  ],

  playback: {
    loop: true,
    speed: 1,
    autoPlay: false,
  },

  templateInfo: {
    sourceTemplateId: 'tpl-active-transport-001',
    sourceTemplateName: '主动运输模板',
  },
}